add pgcat connection pooler/proxy to indexer stack
autonomys/astral pull request #1044
Opened 2024-12-19 15:07 UTC by DaMandal0rian

2024-12-20 17:15 UTC, marc-aurele-besner commented
```
dictionary_subquery_node-1   | 2024-12-20T17:14:33.019Z <db> ERROR undefined Error: Unable to connect to the database
dictionary_subquery_node-1   | Cause: ConnectionRefusedError: connect ECONNREFUSED 172.18.0.3:6432
consensus_subquery_node-1    | 2024-12-20T17:14:33.255Z <db> ERROR undefined Error: Unable to connect to the database
consensus_subquery_node-1    | Cause: ConnectionRefusedError: connect ECONNREFUSED 172.18.0.3:6432
files_subquery_node-1        | 2024-12-20T17:14:33.275Z <db> ERROR undefined Error: Unable to connect to the database
files_subquery_node-1        | Cause: ConnectionRefusedError: connect ECONNREFUSED 172.18.0.3:6432
```
I get these errors from all services that try to contract the db with these changes

2024-12-24 12:32 UTC, clostao approved these changes

2024-12-24 12:35 UTC, marc-aurele-besner requested changes
None of the services seems to be able to communicate with the db

2025-01-20 17:10 UTC, marc-aurele-besner requested changes
We need to point hasura to pgcat host

2025-01-20 17:10 UTC, marc-aurele-besner commented on docker-compose.yml
> +      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:6432/${DB_DATABASE}
```suggestion
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@pgcat:6432/${DB_DATABASE}
```

2025-01-20 17:10 UTC, marc-aurele-besner commented on docker-compose.yml
> +      HASURA_GRAPHQL_DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:6432/${DB_DATABASE} # Main database connection
```suggestion
      HASURA_GRAPHQL_DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@pgcat:6432/${DB_DATABASE} # Main database connection
```

2025-01-20 18:08 UTC, marc-aurele-besner approved these changes
LGTM 🙇‍♂️

2025-01-20 18:15 UTC, merged