Cleanup indexers
autonomys/astral pull request #955
Opened 2024-11-15 17:09 UTC by marc-aurele-besner

## Cleanup indexers

- Remove all SubSquids projects
- Update and cleanup SubQuery projects
- Remove unsued SubQuery project (Gemini-3G & Gemini-3H)
- Improve root readme to remove mention of SubSquid

2024-11-15 18:52 UTC, clostao approved these changes

2024-11-18 10:02 UTC, DaMandal0rian requested changes

2024-11-18 10:02 UTC, DaMandal0rian commented on .github/workflows/gh-container-image.yml
This workflow file can be deleted

2024-11-18 10:02 UTC, DaMandal0rian commented on docker-compose.yml
> +      - --batch-size=15
can this be increased now with the latest fix?

2024-11-18 11:17 UTC, clostao approved these changes

2024-11-18 13:45 UTC, DaMandal0rian approved these changes

2024-11-18 13:57 UTC, merged